version: '3.7'
services:
  terraform:
   build:
    context: .
    dockerfile: terraform.dockerfile
  website:
   image: website
   build:
    context: .
   ports:
    - "80"
  unit-tests:
    volumes:
      - "$PWD:/app"
    build:
      context: .
      dockerfile: rspec.dockerfile
    command:
      - --pattern
      - /app/spec/unit/*_spec.rb
